image: docker:git
services:
- docker:dind

stages: 
  - build
  - deploy
build:
  stage: build
  variables:
    dockerId: $dockerId
    dockerPassword: $dockerPassword
  script: |
    docker login -u $dockerId -p $pswd
    docker-compose build
    docker-compose push


