stages: 
  - build
  - deploy
build:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  stage: build
  variables:
    dockerId: $dockerId
    dockerPassword: $dockerPassword
  script: |
    echo $dockerId
    echo $dockerPassword
    docker login -u $dockerId -p $dockerPassword
    docker-compose build
    docker-compose push
deploy:
  image: microsoft/azure-cli
  stage: deploy
  variables:
    userName: $principalName
    password: $principalPassword
    tenant: $principalTenant
  script: | 
    az login --service-principal -u $userName -p $password --tenant $tenant
    az aks install-cli
    az aks list
    az aks get-credentials --resource-group kubernetes-monorepo --name kubernetes-mono
    kubectl get nodes


