image: docker:git
services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

stages: 
  - build
  - deploy
build:
  stage: build
  variables:
    dockerId: $dockerId
    dockerPassword: $dockerPassword
  script: |
    echo $dockerId
    echo $dockerPassword
    docker login -u $dockerId -p $dockerPassword
    docker-compose build
    docker-compose push
deploy:
  image: microsoft/azure-cli
  stage: deploy
  variables:
    azureUsername: $azureUsername
    azurePassword: $azurePassword
  script: az login -u $azureUsername -p $azurePassword


