# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
variables:
- group: mono-repo
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    docker login -u $dockerId -p $pswd
    docker-compose build
    docker-compose push
  env:
    pswd: $(dockerPassword)
    dockerId: $(dockerId)
