version: '3.2'
volumes:
    database_data:
        driver: local
services: 
  server:
    image: sepehr500/mono-server-example:latest
    build: ./server
    # volumes: 
      # - ./server/src:/app/src 
    ports:
      - "8080:8080"
  frontend:
    image: sepehr500/mono-frontend-example:latest
    container_name: frontend
    build: ./spa
    ports:
      - '80:80'