version: '3.2'
volumes:
    database_data:
        driver: local
services: 
  server:
    build: ./server
    volumes: 
      - ./server/src:/app/src 
    ports:
      - "8080:8080"
    command: npm run dev
