apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-server-deploy
  labels:
    app: mono-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mono-server
  template:
    metadata:
      labels:
        app: mono-server
        version: '5'
    spec:
      containers:
      - name: mono-server
        image: sepehr500/mono-server-example:latest
        ports:
        - containerPort: 30576
---
apiVersion: v1
kind: Service
metadata:
  name: mono-server
spec:
  ports:
  - port: 30576
  selector:
    app: mono-server
    version: '5'
---
apiVersion: v1
kind: Service
metadata:
  name: mono-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mono-frontend
    version: '5'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-frontend
spec:
  selector:
    matchLabels:
      app: mono-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: mono-frontend
        version: '5'
    spec:
      containers:
      - name: mono-frontend
        image: sepehr500/mono-frontend-example:latest
        ports:
        - containerPort: 80
